Ext.define('CIAM_app.store.nazioniStore', {
	extend: 'Ext.data.Store',
	config: {
		model: 'CIAM_app.model.nazioniModel',
		data: [
		{value:'',
			text:''
		},{
			value: 'IT',
			text: 'Italia'
		}, {
			value: 'FR',
			text: 'Francia'
		}, {
			value: 'AF',
			text: 'Afghanistan'
		}, {
			value: 'AL',
			text: 'Albania'
		}, {
			value: 'DZ',
			text: 'Algeria'
		}, {
			value: 'AD',
			text: 'Andorra'
		}, {
			value: 'AO',
			text: 'Angola'
		}, {
			value: 'AI',
			text: 'Anguilla'
		}, {
			value: 'AQ',
			text: 'Antartide'
		}, {
			value: 'AG',
			text: 'Antigua e Barbuda'
		}, {
			value: 'AN',
			text: 'Antille Olandesi'
		}, {
			value: 'SA',
			text: 'Arabia Saudita'
		}, {
			value: 'AR',
			text: 'Argentina'
		}, {
			value: 'AM',
			text: 'Armenia'
		}, {
			value: 'AW',
			text: 'Aruba'
		}, {
			value: 'AU',
			text: 'Australia'
		}, {
			value: 'AT',
			text: 'Austria'
		}, {
			value: 'AZ',
			text: 'Azerbaigian'
		}, {
			value: 'BS',
			text: 'Bahamas'
		}, {
			value: 'BH',
			text: 'Bahrein'
		}, {
			value: 'BD',
			text: 'Bangladesh'
		}, {
			value: 'BB',
			text: 'Barbados'
		}, {
			value: 'BE',
			text: 'Belgio'
		}, {
			value: 'BZ',
			text: 'Belize'
		}, {
			value: 'BJ',
			text: 'Benin'
		}, {
			value: 'BM',
			text: 'Bermuda'
		}, {
			value: 'BT',
			text: 'Bhutan'
		}, {
			value: 'BY',
			text: 'Bielorussia'
		}, {
			value: 'BO',
			text: 'Bolivia'
		}, {
			value: 'BA',
			text: 'Bosnia-Erzegovina'
		}, {
			value: 'BW',
			text: 'Botswana'
		}, {
			value: 'BR',
			text: 'Brasile'
		}, {
			value: 'BN',
			text: 'Brunei'
		}, {
			value: 'BG',
			text: 'Bulgaria'
		}, {
			value: 'BF',
			text: 'Burkina Faso'
		}, {
			value: 'BI',
			text: 'Burundi'
		}, {
			value: 'KH',
			text: 'Cambogia'
		}, {
			value: 'CM',
			text: 'Camerun'
		}, {
			value: 'CA',
			text: 'Canada'
		}, {
			value: 'CV',
			text: 'Capo Verde'
		}, {
			value: 'TD',
			text: 'Ciad'
		}, {
			value: 'CL',
			text: 'Cile'
		}, {
			value: 'CN',
			text: 'Cina'
		}, {
			value: 'CY',
			text: 'Cipro'
		}, {
			value: 'VA',
			text: 'Città del Vaticano'
		}, {
			value: 'CO',
			text: 'Colombia'
		}, {
			value: 'KM',
			text: 'Comore'
		}, {
			value: 'CG',
			text: 'Congo'
		}, {
			value: 'CD',
			text: 'Congo - Repubblica Dem. del'
		}, {
			value: 'KR',
			text: 'Corea'
		}, {
			value: 'KP',
			text: 'Corea del Nord'
		}, {
			value: 'CI',
			text: 'Costa di Avorio'
		}, {
			value: 'CR',
			text: 'Costa Rica'
		}, {
			value: 'HR',
			text: 'Croazia'
		}, {
			value: 'CU',
			text: 'Cuba'
		}, {
			value: 'DK',
			text: 'Danimarca'
		}, {
			value: 'DM',
			text: 'Dominica'
		}, {
			value: 'EC',
			text: 'Ecuador'
		}, {
			value: 'EG',
			text: 'Egitto'
		}, {
			value: 'SV',
			text: 'El Salvador'
		}, {
			value: 'AE',
			text: 'Emirati Arabi'
		}, {
			value: 'ER',
			text: 'Eritrea'
		}, {
			value: 'EE',
			text: 'Estonia'
		}, {
			value: 'ET',
			text: 'Etiopia'
		}, {
			value: 'FJ',
			text: 'Fiji'
		}, {
			value: 'PH',
			text: 'Filippine'
		}, {
			value: 'FI',
			text: 'Finlandia'
		}, {
			value: 'GA',
			text: 'Gabon'
		}, {
			value: 'GM',
			text: 'Gambia'
		}, {
			value: 'GE',
			text: 'Georgia'
		}, {
			value: 'GS',
			text: 'Georgia del Sud e Isole Sandwich Meridionali'
		}, {
			value: 'DE',
			text: 'Germania'
		}, {
			value: 'GH',
			text: 'Ghana'
		}, {
			value: 'JM',
			text: 'Giamaica'
		}, {
			value: 'JP',
			text: 'Giappone'
		}, {
			value: 'GI',
			text: 'Gibilterra'
		}, {
			value: 'DJ',
			text: 'Gibuti'
		}, {
			value: 'JO',
			text: 'Giordania'
		}, {
			value: 'UK',
			text: 'Gran Bretagna'
		}, {
			value: 'GR',
			text: 'Grecia'
		}, {
			value: 'GD',
			text: 'Grenada'
		}, {
			value: 'GL',
			text: 'Groenlandia'
		}, {
			value: 'GP',
			text: 'Guadalupe'
		}, {
			value: 'GU',
			text: 'Guam'
		}, {
			value: 'GT',
			text: 'Guatemala'
		}, {
			value: 'GF',
			text: 'Guiana francese'
		}, {
			value: 'GN',
			text: 'Guinea'
		}, {
			value: 'GQ',
			text: 'Guinea equatoriale'
		}, {
			value: 'GW',
			text: 'Guinea-Bissau'
		}, {
			value: 'GY',
			text: 'Guyana'
		}, {
			value: 'HT',
			text: 'Haiti'
		}, {
			value: 'HN',
			text: 'Honduras'
		}, {
			value: 'HK',
			text: 'Hong Kong SAR'
		}, {
			value: 'IN',
			text: 'India'
		}, {
			value: 'ID',
			text: 'Indonesia'
		}, {
			value: 'IR',
			text: 'Iran'
		}, {
			value: 'IQ',
			text: 'Iraq'
		}, {
			value: 'IE',
			text: 'Irlanda'
		}, {
			value: 'IS',
			text: 'Islanda'
		}, {
			value: 'BV',
			text: 'Isola Bouvet'
		}, {
			value: 'KY',
			text: 'Isole Cayman'
		}, {
			value: 'CX',
			text: 'Isole Christmas'
		}, {
			value: 'CC',
			text: 'Isole Cocos (Keeling)'
		}, {
			value: 'CK',
			text: 'Isole Cook'
		}, {
			value: 'FK',
			text: 'Isole Falkland (Islas Malvinas)'
		}, {
			value: 'FO',
			text: 'Isole Faroe'
		}, {
			value: 'HM',
			text: 'Isole Heard e Mcdonald'
		}, {
			value: 'MP',
			text: 'Isole Marianne Settentrionali'
		}, {
			value: 'MH',
			text: 'Isole Marshall'
		}, {
			value: 'UM',
			text: 'Isole minori degli Stati Uniti'
		}, {
			value: 'NF',
			text: 'Isole Norfolk'
		}, {
			value: 'SB',
			text: 'Isole Salomone'
		}, {
			value: 'SJ',
			text: 'Isole Svalbard e Jan Mayen'
		}, {
			value: 'TC',
			text: 'Isole Turks e Caicos'
		}, {
			value: 'VG',
			text: 'Isole Vergini (GB)'
		}, {
			value: 'VI',
			text: 'Isole Vergini (USA)'
		}, {
			value: 'WF',
			text: 'Isole Wallis e Futuna'
		}, {
			value: 'IL',
			text: 'Israele'
		}, {
			value: 'YU',
			text: 'Iugoslavia'
		}, {
			value: 'KZ',
			text: 'Kazakistan'
		}, {
			value: 'KE',
			text: 'Kenya'
		}, {
			value: 'KG',
			text: 'Kirghizistan'
		}, {
			value: 'KI',
			text: 'Kiribati'
		}, {
			value: 'KW',
			text: 'Kuwait'
		}, {
			value: 'LA',
			text: 'Laos'
		}, {
			value: 'LS',
			text: 'Lesotho'
		}, {
			value: 'LV',
			text: 'Lettonia'
		}, {
			value: 'LB',
			text: 'Libano'
		}, {
			value: 'LR',
			text: 'Liberia'
		}, {
			value: 'LY',
			text: 'Libia'
		}, {
			value: 'LI',
			text: 'Liechtenstein'
		}, {
			value: 'LT',
			text: 'Lituania'
		}, {
			value: 'LU',
			text: 'Lussemburgo'
		}, {
			value: 'MO',
			text: 'Macao'
		}, {
			value: 'MK',
			text: 'Macedonia - Ex Repubblica Iugoslava di'
		}, {
			value: 'MG',
			text: 'Madagascar'
		}, {
			value: 'MW',
			text: 'Malawi'
		}, {
			value: 'MV',
			text: 'Maldive'
		}, {
			value: 'MY',
			text: 'Malesia'
		}, {
			value: 'ML',
			text: 'Mali'
		}, {
			value: 'MT',
			text: 'Malta'
		}, {
			value: 'MA',
			text: 'Marocco'
		}, {
			value: 'MQ',
			text: 'Martinica'
		}, {
			value: 'MR',
			text: 'Mauritania'
		}, {
			value: 'MU',
			text: 'Mauritius'
		}, {
			value: 'YT',
			text: 'Mayotte'
		}, {
			value: 'MX',
			text: 'Messico'
		}, {
			value: 'FM',
			text: 'Micronesia'
		}, {
			value: 'MD',
			text: 'Moldavia'
		}, {
			value: 'MC',
			text: 'Monaco'
		}, {
			value: 'MN',
			text: 'Mongolia'
		}, {
			value: 'MS',
			text: 'Montserrat'
		}, {
			value: 'MZ',
			text: 'Mozambico'
		}, {
			value: 'MM',
			text: 'Myanmar'
		}, {
			value: 'NA',
			text: 'Namibia'
		}, {
			value: 'NR',
			text: 'Nauru'
		}, {
			value: 'NP',
			text: 'Nepal'
		}, {
			value: 'NI',
			text: 'Nicaragua'
		}, {
			value: 'NE',
			text: 'Niger'
		}, {
			value: 'NG',
			text: 'Nigeria'
		}, {
			value: 'NU',
			text: 'Niue'
		}, {
			value: 'NO',
			text: 'Norvegia'
		}, {
			value: 'NC',
			text: 'Nuova Caledonia'
		}, {
			value: 'NZ',
			text: 'Nuova Zelanda'
		}, {
			value: 'OM',
			text: 'Oman'
		}, {
			value: 'NL',
			text: 'Paesi Bassi'
		}, {
			value: 'PK',
			text: 'Pakistan'
		}, {
			value: 'PW',
			text: 'Palau'
		}, {
			value: 'PA',
			text: 'Panama'
		}, {
			value: 'PG',
			text: 'Papua Nuova Guinea'
		}, {
			value: 'PY',
			text: 'Paraguay'
		}, {
			value: 'PE',
			text: 'Perù'
		}, {
			value: 'PN',
			text: 'Pitcairn'
		}, {
			value: 'PF',
			text: 'Polinesia francese'
		}, {
			value: 'PL',
			text: 'Polonia'
		}, {
			value: 'PT',
			text: 'Portogallo'
		}, {
			value: 'PR',
			text: 'Puerto Rico'
		}, {
			value: 'QA',
			text: 'Qatar'
		}, {
			value: 'CZ',
			text: 'Repubblica Ceca'
		}, {
			value: 'CF',
			text: 'Repubblica Centrafricana'
		}, {
			value: 'DO',
			text: 'Repubblica Dominicana'
		}, {
			value: 'RE',
			text: 'Reunion'
		}, {
			value: 'RO',
			text: 'Romania'
		}, {
			value: 'RW',
			text: 'Ruanda'
		}, {
			value: 'RU',
			text: 'Russia'
		}, {
			value: 'KN',
			text: 'Saint Kitts e Nevis'
		}, {
			value: 'LC',
			text: 'Saint Lucia'
		}, {
			value: 'PM',
			text: 'Saint Pierre et Miquelon'
		}, {
			value: 'VC',
			text: 'Saint Vincent e Grenadine'
		}, {
			value: 'WS',
			text: 'Samoa'
		}, {
			value: 'AS',
			text: 'Samoa Americane'
		}, {
			value: 'SM',
			text: 'San Marino'
		}, {
			value: 'SH',
			text: 'Sant Elena'
		}, {
			value: 'ST',
			text: 'Sao Tome e Principe'
		}, {
			value: 'SN',
			text: 'Senegal'
		}, {
			value: 'SC',
			text: 'Seychelles'
		}, {
			value: 'SL',
			text: 'Sierra Leone'
		}, {
			value: 'SG',
			text: 'Singapore'
		}, {
			value: 'SY',
			text: 'Siria'
		}, {
			value: 'SK',
			text: 'Slovacchia'
		}, {
			value: 'SI',
			text: 'Slovenia'
		}, {
			value: 'SO',
			text: 'Somalia'
		}, {
			value: 'ES',
			text: 'Spagna'
		}, {
			value: 'LK',
			text: 'Sri Lanka'
		}, {
			value: 'US',
			text: 'Stati Uniti'
		}, {
			value: 'ZA',
			text: 'Sudafrica'
		}, {
			value: 'SD',
			text: 'Sudan'
		}, {
			value: 'SR',
			text: 'Suriname'
		}, {
			value: 'SE',
			text: 'Svezia'
		}, {
			value: 'CH',
			text: 'Svizzera'
		}, {
			value: 'SZ',
			text: 'Swaziland'
		}, {
			value: 'TJ',
			text: 'Tagikistan'
		}, {
			value: 'TH',
			text: 'Tailandia'
		}, {
			value: 'TW',
			text: 'Taiwan'
		}, {
			value: 'TZ',
			text: 'Tanzania'
		}, {
			value: 'TF',
			text: 'Territori australi francesi'
		}, {
			value: 'IO',
			text: 'Territori inglesi dell Oceano Indiano'
		}, {
			value: 'TP',
			text: 'Timor Est'
		}, {
			value: 'TG',
			text: 'Togo'
		}, {
			value: 'TK',
			text: 'Tokelau'
		}, {
			value: 'TO',
			text: 'Tonga'
		}, {
			value: 'TT',
			text: 'Trinidad e Tobago'
		}, {
			value: 'TN',
			text: 'Tunisia'
		}, {
			value: 'TR',
			text: 'Turchia'
		}, {
			value: 'TM',
			text: 'Turkmenistan'
		}, {
			value: 'TV',
			text: 'Tuvalu'
		}, {
			value: 'UA',
			text: 'Ucraina'
		}, {
			value: 'UG',
			text: 'Uganda'
		}, {
			value: 'HU',
			text: 'Ungheria'
		}, {
			value: 'UY',
			text: 'Uruguay'
		}, {
			value: 'UZ',
			text: 'Uzbekistan'
		}, {
			value: 'VU',
			text: 'Vanuatu'
		}, {
			value: 'VE',
			text: 'Venezuela'
		}, {
			value: 'VN',
			text: 'Vietnam'
		}, {
			value: 'YE',
			text: 'Yemen'
		}, {
			value: 'ZM',
			text: 'Zambia'
		}, {
			value: 'ZW',
			text: 'Zimbabwe'
		}]
	}
});