Ext.define('CIAM_app.view.Screensaver', {
	extend: 'Ext.Panel',
	xtype: 'screensaver',
	fullscreen: true,
	requires: ['Ext.InfiniteCarousel', 'Ext.Img', 'Ext.util.DelayedTask', 'Ext.Carousel'],
	config: {
		title: 'Carousel',
		iconCls: 'compose',
		hidden: true,
		items: [{
			xtype: 'infinitecarousel',
			delay: 4000,
			centered: true,
			height: '100%',
			width: '100%',
			items: [{
				xtype: 'image',
				src: 'gallery/bioedilizia/01.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/02.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/03.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/04.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/05.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/06.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/07.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/08.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/09.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/10.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/11.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/12.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/13.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/14.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/15.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/16.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/17.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/18.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/19.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/20.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/21.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/22.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/23.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/24.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/25.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/26.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/27.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/28.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/29.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/30.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/31.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/32.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/33.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/34.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/35.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/36.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/37.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/38.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/39.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/40.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/41.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/42.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/43.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/44.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/45.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/46.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/47.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/48.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/49.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/50.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/51.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/52.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/53.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/54.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/55.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/56.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/57.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/58.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/59.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/60.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/61.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/62.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/63.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/64.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/65.jpg'
			}, {
				xtype: 'image',
				src: 'gallery/bioedilizia/66.jpg'
			}]
		}]
	},
	initialize: function() {
		this.element.on('tap', function() {
			this.tap();
		}, this);
	},
	tap: function() {
		task.cancel();
		var docked_bar = Ext.getCmp('mainview').getDockedItems()[0];
		Ext.getCmp('mainview').setActiveItem(0);
		docked_bar.setHidden(false);
		task.delay(delay);
	}
});